version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD

services:
  mysqldb:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - latestDataVolume:/var/lib/mysql
      - ./backend/db-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_HOST: $MYSQL_HOST

  nginxproxy:
    depends_on:
      - backendserver
      - frontendserver
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8008:80"

  backendserver:
    build:
      context: ./backend
      target: dev
    depends_on:
      - mysqldb
    volumes:
      - ./backend:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - $API_PORT:$API_PORT
    environment:
      <<: *common-variables
      PORT: $API_PORT
      NODE_ENV: development

  frontendserver:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
    volumes:
      - ./frontend:/src
      - /src/node_modules
    ports:
      - $CLIENT_PORT:$CLIENT_PORT

  mysqladminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb

volumes:
  latestDataVolume:
